class Devicetype
  include MongoMapper::Document

  key :name, 		String		#product name
  key :description, String		#optional description
  key :secret,		String		#product secret code, which will be stored in every device instance of this product, this secret code is generated by system automatically, use GET devicetype to read this secret
  key :vendor,		String		#vendor name
  key :metrics,		Array		#Array of metricID which point to instance of Metric

end
